web:
  build: . 
  ports:
    - "80:80"
  volumes:
    - src/:/var/www/html
  links:
    - db
db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: drupal
    MYSQL_USER: user
    MYSQL_PASSWORD: password
